name: Actions Runner Controller Demo
on:
  workflow_dispatch:

jobs:
  Explore-GitHub-Actions:
  
    # You need to use the INSTALLATION_NAME from the previous step
    runs-on: arc-runner-set
    steps:
    - run:  | 
            sudo apt-get update && sudo apt-get -y upgrade
            sudo apt-get install software-properties-common -y
            sudo apt update && sudo apt upgrade -y 
            sudo apt install curl unzip  -y
            sudo curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            sudo unzip awscliv2.zip
            sudo ./aws/install
            aws --version
            aws s3 ls --region us-east-1

          
